### ISSUE TITLE
Personalization -> WAI-Adapt specifications ?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-personalization-standards#9]
_[updated 6 April]_
_Proposal under consideration is:_

**"WAI-Adapt specifications"**
* **WAI-Adapt: Content Module**
* **WAI-Adapt: Help and Support Module**
* **WAI-Adapt: Tools Module**
* ... etc.

_Please at least skim:_
* **[Adapt Specifications Overview | Adapt Overview](https://deploy-preview-8--wai-personalization-standards.netlify.app/personalization/)** - rough example of Adapt specifications in use
*  [issue 7](https://github.com/w3c/wai-personalization-standards/issues/7) with context, links to minutes, previous ideas
* [e-mail thread starting 12 March](https://lists.w3.org/Archives/Public/w3c-wai-eo/2022JanMar/0041.html) with different perspectives

**Comment by iadawn** [comment]
+1

**Comment by daniel-montalvo** [comment]
+1

**Comment by becka11y** [comment]
Since branding personalization work, #7 , is closed, I am commenting here.  Some members of personalization had concerns with Adapt.  Another suggestion has been put forward, APT – Adaptable Personalisation Techniques.  Is this something that can be considered?

**Comment by KimPatch** [comment]
Just heard about this – here a couple of thoughts. 
- One difference between personalization and adapt is it's obvious that you're personalizing for a person, but with adapt it's not clear if the person or the technology is adapting. This might be confusing to folks. 
- Personalization is a description, and so is the phrase associated with APT – Adaptable Personalisation Technique, while adapt is an imperative, which makes for a more difficult label.
- It's also tough to use a single word that's not a description because you might employ that word when you're talking about the thing itself. I'm picturing it getting confusing in a "Who's on First" sort of way trying to explain "adapt" the standard without using adapt the word. For instance, the phrase "adapt the standard" becomes ambiguous…

**Comment by shawna-slh** [comment]
Hi @KimPatch "Personalization" didn't work. Janina and others explain why in some of the minutes or comment available from https://github.com/w3c/wai-personalization-standards/issues/7

I think if we go with "WAI-Adapt", it makes sense for people to use the word adapt when talking about it. Next comment has more options...

**Comment by shawna-slh** [comment]
[6 April 2022 WAI Coordination Call minutes](https://www.w3.org/2022/04/06-waicc-minutes.html#t05)

Agreement on:
* "WAI-Adapt" or "WAI-ADAPT"

Open:
* ? capitalization&mdash; "WAI-Adapt" or "WAI-ADAPT"
* ? short phrase &mdash; "Adaptable Personalizable Technologies" is complex

**Comment by shawna-slh** [comment]
I updated **[draft WAI-Adapt Overview](https://deploy-preview-8--wai-personalization-standards.netlify.app/personalization/)**
* Draft first sentence of the [Introduction](https://deploy-preview-8--wai-personalization-standards.netlify.app/personalization/#introduction):
   > WAI-Adapt specifications enable users to personalize how content is presented in order to meet their needs and preferences.
* Summary has a little more info in short simple sentencs, including "why Adapt".

I don't think we want "Adaptable Personalizable Techniques|Technologies". It's too complex to understand and even say. I think we can convey the point more simply. Some ideas are in the draft:
* Enabling users to adapt content
* Enabling users to adapt content presentation
* Enabling users to change content presentation
* Enabling users to personalize content presentation

I wonder about the issues with "change", "adapt", "personalize" for the simple description for the lay-person (a person without professional or specialized knowledge in a particular subject)?

**Comment by KimPatch** [comment]
I understand that the goal is for an alternative to personalization – my comment was that I think
WAI APT – Adaptable Personalization Techniques 
works better than 
WAI Adapt 
because it avoids the Who's responsible, Imperative, and Who's-on-first issues (details above). I guess that was buried in my longer explanation.
